In [1]:
import numpy as np

###### 1. What is a Python library? Why do we use Python libraries?

Python library is pre-defined library. Which contain lot of function and classes already. Libraries use for many purposes such as increasing efficiency, reusability of code.

###### 2. What is the difference between Numpy array and List?

1. Numpy array are stores same type of datatypes. List contain different type of datatypes.
2. Numpy are faster then the list.
3. Numpy array size is fix ones we create array then the size of array is fixed but the size of list is dynamic.
4. Numpy array having different functions rather than the list.

###### 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
a = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

print(f'Shape = {a.shape} \nSize = {a.size} \nDimension = {a.ndim}')

Shape = (3, 4) 
Size = 12 
Dimension = 2


###### 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[0]

array([1, 2, 3, 4])

###### 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[2,3]

12

###### 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

###### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
x = np.random.rand(3,3)
x

array([[0.33164026, 0.91901757, 0.03802453],
       [0.45098338, 0.37575558, 0.90506565],
       [0.35770615, 0.14349601, 0.49776675]])

###### 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x[:,:,np.newaxis]

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [8]:
np.expand_dims(x,axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

###### 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

###### 11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [10]:
a = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
b = np.matrix([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [11]:
a

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [12]:
b

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [13]:
np.multiply(a,b)

matrix([[  1,   4,   9,  16],
        [ 25,  36,  49,  64],
        [ 81, 100, 121, 144]])

In [14]:
a + b

matrix([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])

In [15]:
b - a

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [16]:
b / a

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])